name: tests-order

on:
  pull_request:
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd order && yarn && yarn test:ci
